Handle SIGHUP to cause the log to rotate/get a new one manually
ZeroCM/zcm pull request #494
Opened 2024-10-08 13:47 UTC by andybarry

The zcm-logger help says that SIGHUP should cause the log to rotate, but that didn't work for me.

I have implemented that functionality here.

2024-10-09 09:27 UTC, jbendes commented
This looks great thanks for the contribution! What are your thoughts on behavior if `args.rotate <= 0`?

2024-10-12 13:40 UTC, andybarry commented
Good point.  Perhaps we only support SIGHUP if rotate or increment is used?  I'll implement that and add a print if SIGHUP is received and we're not in that configuration.

2024-10-14 15:53 UTC, andybarry commented
I've updated the PR with a check that ignores SIGHUP if the user hasn't specified `--increment` or `--rotate`.  I also was a bit confused about how to not have `--increment` specified, so I changed the error message there to add some more context, hopefully that makes sense to you.

2024-10-18 17:52 UTC, jbendes requested changes

2024-10-18 17:52 UTC, jbendes commented on tools/cpp/logger/main.cpp
> +            cerr << "ERROR.  --increment and --rotate can't both be used. Note that if you don't want --increment, you must specify a log filename." << endl;
Can we make sure to adhere to max line length here? Run `zcm-logger -h` to see what I mean

2024-10-18 17:52 UTC, jbendes commented on tools/cpp/logger/main.cpp
> +        if (got_sighup && (args.auto_increment || (args.rotate > 0))) {
Can just check `got_sighup`

2024-10-18 17:52 UTC, jbendes commented on tools/cpp/logger/main.cpp
> +    signal(SIGHUP,  sighup_handler);
You can register this handler only in the cases you want to actually handle the signal. Specifically `args.auto_increment || args.rotate > 0`

2024-10-18 20:57 UTC, andybarry commented
All updated, note there is a slight behavior change in that if we don't register SIGHUP handler, the logger will quit when it receives a SIGHUP.

2024-10-22 21:30 UTC, jbendes commented
Ahh good point. Let's preserve the old behavior with the registering the signal. But you can just not set the variable in the callback unless it's relevant to

2024-10-28 14:47 UTC, closed without merging